name: Publish NuGet

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: Run unit tests
      run: dotnet test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Fetch git tags history
        run: git fetch --prune --unshallow
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9
        with:
          versionSpec: '5.1.x'

      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9

      - name: GitVersion Output
        run: echo "NuGetVersion:${{ steps.gitversion.outputs.nuGetVersion }}"
          
      - name: Create package for value converter # leave attributes out of automation, publish excplicitly if needed
        run: dotnet pack Innofactor.EfCoreJsonValueConverter/Innofactor.EfCoreJsonValueConverter.csproj -o ./ -p:PackageVersion=${{steps.gitversion.outputs.nuGetVersion}}
        
      - name: Check directory
        run: ls
